"""DraftPackage and supporting data models for Writer Worker subsystem."""

from enum import StrEnum

from pydantic import BaseModel, Field


class WritingStyle(StrEnum):
    """Supported writing tone & style specifications."""
    AUTHORITATIVE = "AUTHORITATIVE"
    CONVERSATIONAL = "CONVERSATIONAL"
    TECHNICAL = "TECHNICAL"
    ENGAGING = "ENGAGING"
    INSTRUCTIVE = "INSTRUCTIVE"
    EXECUTIVE = "EXECUTIVE"

class DraftValidationScores(BaseModel):
    """Sub-scores breakdown from DraftValidator audit."""

    length_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Word count compliance score")
    citation_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Citation preservation score")
    outline_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Outline section coverage score")
    cta_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Call to action presence score")
    composite_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Weighted composite score")

class DraftPackage(BaseModel):
    """Strongly-typed production draft package generated by WriterWorker."""

    title: str = Field(description="Finalized draft title")
    subtitle: str | None = Field(default=None, description="Optional subtitle or header tagline")
    platform: str = Field(description="Target publishing platform")
    content_format: str = Field(description="Target format structure")
    audience: str = Field(description="Target audience classification")
    objective: str = Field(description="Primary content goal")
    writing_style: WritingStyle = Field(default=WritingStyle.AUTHORITATIVE, description="Writing tone and style")
    draft: str = Field(description="Full markdown body content of the draft")
    draft_version: int = Field(default=1, ge=1, description="Draft revision version number")
    outline: list[str] = Field(default_factory=list, description="Preserved brief outline")
    citations_used: list[dict] = Field(default_factory=list, description="Citations preserved in draft")
    seo_keywords: list[str] = Field(default_factory=list, description="SEO keywords targeted")
    estimated_read_time: str = Field(default="5 min read", description="Estimated reading duration")
    validation_scores: DraftValidationScores = Field(default_factory=DraftValidationScores, description="Validator score details")
    confidence: float = Field(default=0.90, ge=0.0, le=1.0, description="Generation confidence score")
    generation_metadata: dict = Field(
        default_factory=lambda: {
            "generation_number": 1,
            "prompt_version": "v1.0.0",
            "worker_version": "v0.6.4",
        },
        description="Execution telemetry, prompt versions, and worker metadata",
    )
