"""Publisher Worker data models for AI Workforce Core subsystem.

Defines strongly-typed schemas for publish status, platform payloads,
and the final PublicationPackage output produced by the PublisherWorker pipeline.
"""

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from modules.workforce.workers.draft_models import WritingStyle
from modules.workforce.workers.editor_models import EditQualityScores
from modules.workforce.workers.seo_models import SEOScores
from modules.workforce.workers.verification_models import VerificationReport


class PublishStatus(StrEnum):
    """Supported publication outcome statuses."""

    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"


class PlatformPayload(BaseModel):
    """Platform-specific payload generated by the PayloadBuilder.

    Attributes:
        platform: Target platform identifier (e.g. linkedin, x, medium, ghost).
        raw_content: Primary text or markdown content for the post.
        formatted_payload: Platform-specific structured dictionary payload.
        media_urls: Associated media or image URLs.
        target_channels: Target channels, topics, or sub-feed identifiers.
        metadata: Custom metadata dictionary for the platform payload.
    """

    platform: str = Field(description="Target platform identifier")
    raw_content: str = Field(description="Primary content body")
    formatted_payload: dict = Field(default_factory=dict, description="Platform-specific structured payload")
    media_urls: list[str] = Field(default_factory=list, description="Associated media URLs")
    target_channels: list[str] = Field(default_factory=list, description="Target channels or tags")
    metadata: dict = Field(default_factory=dict, description="Custom payload metadata")


class PublicationPackage(BaseModel):
    """Strongly-typed final production output from the PublisherWorker pipeline.

    Attributes:
        platform: Target publishing platform.
        title: Final published content title.
        content: Final content body as published.
        slug: URL-safe slug identifier.
        final_url: Resolved live URL after publication (if available).
        resolved_internal_links: Internal link suggestions resolved to live URLs.
        resolved_external_links: External link suggestions resolved to live URLs.
        schema_markup: JSON-LD schema with all placeholders resolved.
        publish_status: PublishStatus outcome enum.
        scheduled_time: ISO timestamp if post is scheduled.
        published_time: ISO timestamp when post was published.
        platform_post_id: Platform-native post ID or transaction reference.
        platform_metadata: Custom metadata returned by platform adapter.
        verification_report: Forwarded immutable VerificationReport from Fact Checker.
        quality_scores: Forwarded immutable EditQualityScores from Editor.
        seo_scores: Forwarded immutable SEOScores from SEO Worker.
        platform_format: Target content format structure.
        audience: Target audience classification.
        objective: Primary content goal.
        writing_style: Writing tone and style enum.
        publisher_metadata: Execution telemetry and version metadata.
    """

    # Core publishing output
    platform: str = Field(description="Target publishing platform")
    title: str = Field(description="Final published title")
    content: str = Field(description="Final content body")
    slug: str = Field(default="", description="URL-safe slug")
    final_url: str | None = Field(default=None, description="Live published URL")

    # Resolved links & technical SEO
    resolved_internal_links: list[dict] = Field(
        default_factory=list,
        description="Internal links [{anchor_text, target_topic, resolved_url, rationale}]",
    )
    resolved_external_links: list[dict] = Field(
        default_factory=list,
        description="External links [{anchor_text, target_topic, resolved_url, rationale}]",
    )
    schema_markup: dict = Field(
        default_factory=dict,
        description="JSON-LD schema with all placeholders populated",
    )

    # Publication state
    publish_status: PublishStatus = Field(default=PublishStatus.PUBLISHED, description="Publish outcome status")
    scheduled_time: str | None = Field(default=None, description="ISO timestamp if scheduled")
    published_time: str | None = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="ISO timestamp when published",
    )
    platform_post_id: str | None = Field(default=None, description="Platform-native post ID")
    platform_metadata: dict = Field(default_factory=dict, description="Platform adapter response metadata")

    # Forwarded immutable lineage
    verification_report: VerificationReport = Field(description="Immutable VerificationReport from Fact Checker")
    quality_scores: EditQualityScores = Field(description="Immutable EditQualityScores from Editor")
    seo_scores: SEOScores = Field(description="Immutable SEOScores from SEO Worker")

    # Context
    platform_format: str = Field(default="Article", description="Target content format")
    audience: str = Field(default="General", description="Target audience classification")
    objective: str = Field(default="EDUCATIONAL", description="Primary content goal")
    writing_style: WritingStyle = Field(default=WritingStyle.AUTHORITATIVE, description="Writing style enum")

    # Publisher telemetry
    publisher_metadata: dict = Field(
        default_factory=lambda: {
            "publisher_version": "v0.6.8",
            "publish_pass_count": 1,
        },
        description="Execution telemetry and version metadata",
    )
